development:
  certificate: apple_push_notification_production.pem
  certificate_password: 123nikhil

  push:
    host: gateway.sandbox.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.sandbox.push.apple.com
    port: 2196
    poll: 60

production:
  certificate: apple_push_notification_production.pem
  certificate_password: 123nikhil
  airbrake_notify: true
  pid_file: tmp/pids/rapns.pid

  push:
    host: gateway.push.apple.com
    port: 2195
    poll: 2
    connections: 3

  feedback:
    host: feedback.push.apple.com
    port: 2196
    poll: 60